model:
  model_name: resnet
  arch: resnet50
  dropout: 0
  pretrained: True
  resume_ckpt: False

train:
  seed: 123
  model_type: "resnet50" # ["resnet50, resunet"]
  method: "erm" # ["erm", "seg"]
  binary_weight: 0
  epochs: 100
  batch_size: 16
  lr: 5e-4
  wd: 0
  valid_split: val
  model_id: null
  
dataset:
  source: "cxr_p" # options: {"cxr_p", "reflax"}
  sample_ratio: 1
  num_workers: 4
  id_column: "id"
  input_column: "input"
  augmentation: True


wandb:
  project: domino
  group: ''
  log_model: False

